### ISSUE TITLE
Tradução "Single-File Components"

### ISSUE THREAD

**Issue by viniciusdeliz** [nazarepiedady/vue3-docs-pt#1]
Traduzir arquivo guide/scaling-up/sfc.md

**Comment by nazarepiedady** [comment]
@viniciusdeliz neste momento estou aguardando que o projeto seja adicionado a
organização Vue.js Translations só então começarei a dar um jeito de deixar as coisas
mais coordenadas, mas quanto ao ficheiro mencionado eu já o tinha traduzido mas
estive doente e estou recuperando da mesma e só agora tive tempo de atualizar o
repositório.

**Comment by nazarepiedady** [comment]
@viniciusdeliz agradeço o teu interesse em contribuir com o projeto, de momento
uma das contribuições mais valiosas está na leiturabilidade do conteúdo, é preciso
saber o quão agradável está a leitura dos mesmos, se puderes ajudar neste ponto
seria uma grande contribuição.

**Comment by viniciusdeliz** [comment]
> @viniciusdeliz agradeço o teu interesse em contribuir com o projeto, de momento uma das contribuições mais valiosas está na leiturabilidade do conteúdo, é preciso saber o quão agradável está a leitura dos mesmos, se puderes ajudar neste ponto seria uma grande contribuição.

@nazarepiedady no momento tenho disponibilidade apenas para realizar a tradução do conteúdo. Mas futuramente poderei colaborar com a correção e revisão dos arquivos. Deixe-me saber se isto é interessante para o projeto. Até!

**Comment by viniciusdeliz** [comment]
> @viniciusdeliz podes colaborar com a tradução de ficheiros referentes a API da Vue 3, os outros ficheiros encontram-se já em processo de tradução, só a API da Vue 3 está intocável.

Poderiam se ter _issues_ ou alguma outra maneira de a comunidade saber o status e/ou andamento dos itens que precisam de tradução ou revisão? Isso definitivamente iria aumentar a contribuição e a eficiência das colaborações.

**Comment by nazarepiedady** [comment]
@viniciusdeliz irei criar mapa de estrada para o projeto, na funcionalidade de projetos da GitHub para os interessados poderem acompanhar.

**Comment by viniciusdeliz** [comment]
> @viniciusdeliz irei criar mapa de estrada para o projeto, na funcionalidade de projetos da GitHub para os interessados poderem acompanhar.

Alguma novidade com o _roadmap_ ou com a tradução ao menos? Este projeto parece estar parado e sem aceitar a colaboração de outros indivíduos.

**Comment by nazarepiedady** [comment]
@viniciusdeliz peço desculpas pela demora em responder adequadamente aos
teus questionamentos, de fato o projeto não está parado é que como trabalho
de maneira simultânea em vários projetos acabo as vezes por ficar sem atualizar
o repositório:

Atualmente estou a atualizar e a trabalhar nos seguintes repositórios:

- [nodejs.dev](https://github.com/nazarepiedady/nodejs.dev)
- [vitejs/docs-pt](https://github.com/vitejs/docs-pt)
- [vue-router-docs-pt](https://github.com/nazarepiedady/vue-router-docs-pt)
- [windicss-docs-pt](https://github.com/nazarepiedady/windicss-docs-pt)
- [pinia-docs-pt](https://github.com/nazarepiedady/pinia-docs-pt)
- [nuxtjs.org](https://github.com/nazarepiedady/nuxtjs.org)

E mais alguns outros projetos que ainda não cheguei a carregar na minha conta da
GitHub, eu tenciono começar a traduzir a documentação da Nuxt 3, Svelte e Svelte Kit.

@viniciusdeliz na documentação da Vue.js 3 faltam apenas alguns artigos das seções:

* Boas Práticas
  * [Desempenho](https://vue3-docs-pt.netlify.app/guide/best-practices/performance)
  * [Acessibilidade](https://vue3-docs-pt.netlify.app/guide/best-practices/accessibility)
  * [Segurança](https://vue3-docs-pt.netlify.app/guide/best-practices/security)

* Tópicos Adicionais
  * [Questões Frequentes sobre a API de Composição](https://vue3-docs-pt.netlify.app/guide/extras/composition-api-faq)
  * [Reatividade em Profundidade](https://vue3-docs-pt.netlify.app/guide/extras/reactivity-in-depth)
  * [Mecanismo de Interpretação](https://vue3-docs-pt.netlify.app/guide/extras/rendering-mechanism)
  * [Funções de Interpretação e JSX](https://vue3-docs-pt.netlify.app/guide/extras/render-function)
  * [Vue e os Componentes da Web](https://vue3-docs-pt.netlify.app/guide/extras/web-components)
  * [Transformação da Reatividade](https://vue3-docs-pt.netlify.app/guide/extras/reactivity-transform.html)

Depois de terminar de traduzir este conteúdo que falta, apenas sobrará a API, e o projeto apenas será organizado para receber contribuições quando ele for adicionado na organização [vuejs-translations](https://github.com/vuejs-translations/) de onde tudo será coordenado, assim como está acontecendo com o [vitejs/docs-pt](https://github.com/vitejs/docs-pt), porque como atualmente trabalho primariamente desligado da rede e depois carrego as atualizações a grosso não estou com muito tempo sobrando para revisar pedidos de atualizações do repositório principal (PR ou Pull Requests em Inglês).

Para teres uma ideia é só reparares nas horas em que faço algumas atualizações ou a hora que eu escrevo este logo comentário, é que praticamente tenho que virar a noite para fazer algumas coisas. :sweat_smile:

**Comment by viniciusdeliz** [comment]
Agradeço pela resposta e pela sua dedicação com este e demais projetos, @nazarepiedady. A questão é que membros da comunidade querem ajudar a realizar a tradução, mas parece que o projeto está sendo tocado exclusivamente apenas por uma única pessoa. Incluir a possibilidade de outros membros colaborarem com este projeto ajudaria você a liberar tempo para trabalhar em outros projetos, ao passo em que a tradução e revisão andariam de forma mais rápida. Dessa forma, antigos e novos membros da comunidade, e até alguém que está conhecendo o Vue pela primeira vez, teriam acesso à documentação completa em português.

Novamente, não estou requerendo em específico a sua rapidez em realizar a tradução, espero que entenda, mas sim pelo considerável tempo em que o projeto está com o mesmo status de 60%. Ao mesmo tempo em que vejo outros membros não conseguindo colaborar com o projeto, e também notando que não há atualizações contínuas no repositório. 

Adicionalmente, ainda, a antiga documentação do Vue 3, aquela feita com VuePress, estava provavelmente 99% completa. Agora na versão feita com VitePress, muitos dos artigos se repetem quase fielmente, então a maior parte do trabalho seria uma espécie de migração ou adaptação do conteúdo, ao invés da refação do zero, como vejo que está acontecendo agora. Isto torna o trabalho muito mais exaustivo e custoso, ainda mais trabalhando sozinho.

Então, isso é o que estou tentando comunicar desde o princípio. Todos os possíveis usuários falantes de português que acessam a documentação oficial do Vue adorariam contar com a execução deste projeto o mais rápido possível.

**Comment by nazarepiedady** [comment]
@viniciusdeliz a documentação da Vue 3 antiga foi escrita quando a mesma estava na versão de pré-visualização e beta, e os artigos foram reescritos várias vezes, eu mesmo as vezes tenho que pausar algumas traduções de vez em quando para reescrever alguns artigos que foram reescritos na versão original em Inglês.

E existe também alguns detalhes nesta tradução para o Português em relação as que normalmente são feitas, eu uso a base da língua presente em todas as variações da língua, é raro a presença do uso do estrangeirismo (mistura de termos em Inglês com o conteúdo em Português), e não faço uso de traduções literais (Português que usa estrutura em Inglês), depois destes existe mais muitos outros.

Eu não entendo o porquê de certas pessoas recusarem-se a contribuir com revisões e analise da qualidade do vasto conteúdo que já está traduzido, e levantar questões e debater sobre elas por possíveis melhorias, o que parece é que as pessoas não estão interessadas na qualidade do projeto ou contribuir de fato mas sim apenas parecer que contribuem ou participar por simples ato de participar, porque se a intenção de traduzir for real eu já disse em que aspeto a contribuição seria valiosa e não aparece ninguém para fazer porque envolver ler a documentação integralmente, és o único que insiste em querer participar mas assim como outros não queres participar na parte que eu digo ser mais valiosa do projeto que é a **qualidade do conteúdo que já está traduzido**, porque se a preocupação é de que o projeto parece não avançar eu garanto-lhe que as traduções disponíveis estão em igualdade com o original no requisito de atualidade.

Eu agradeço pelo seu interesse, e se a vontade de traduzir permanece, a pasta dos documentos da **`API`** encontram-se ainda por traduzir, podes contribuir nelas, mas não posso garantir brevidade nas revisões e visões com o ramo principal do repositório, porque estou concentrado no material que estou a traduzir no momento e na revisão da qualidade do conteúdo que já está traduzido, eu estou a fazer este trabalho junto de um profissional versado em línguas que está ao meu serviço.

**Comment by nazarepiedady** [comment]
@viniciusdeliz poderias ajudar também a traduzir os seguintes materiais [pt.javascript.info](https://github.com/javascript-tutorial/pt.javascript.info) e [you-dont-know-js](https://github.com/cezaraugusto/You-Dont-Know-JS)?

Enquanto estiveres a traduzir os documentos da pasta **`API`**, poderias ver em que poderias ajudar nos projetos que mencionei? Os projetos em si são muito maior do que este e estão a procura de colaboradores ativos.

O teu zelo e interesse é louvável, continue assim e melhore naquilo que tiveres que melhorar. :relaxed: 

Muito obrigado pelos pontos que apresentou.
