### ISSUE TITLE
docs(pt):  translate all files inside `api/` folder

### ISSUE THREAD

**Issue by viniciusdeliz** [nazarepiedady/vue3-docs-pt#3]
Translate the following files:

- [x] application.md
- [x] #5
- [x] #6
- [x] #7
- [x] #8
- [x] #9
- [x] #10
- [x] #11
- [x] #12
- [x] #13
- [x] #14
- [x] #15
- [x] #16
- [x] #17
- [x] #18
- [x] #19
- [x] #21
- [x] #22
- [x] #23
- [x] #25
- [x] #24
- [x] #26
- [x] #27
- [x] #28
- [x] #29
- [x] #30

**Comment by nazarepiedady** [comment]
@viniciusdeliz que bom, agora sempre que terminares a tradução de um documento é só
confirmares o feito na sua respetiva caixa de confirmação para indicares o progresso. :+1:

**Comment by viniciusdeliz** [comment]
@nazarepiedady can you convert each task to an issue using the task shortcut? I'm not allowed to do that in this repo.

**Comment by nazarepiedady** [comment]
@viniciusdeliz sorry for the delay, I already rebased your changes.

I suggest you create a single issue for each file you will translate.

**Comment by ogilvieira** [comment]
I think has some issues didn't updated. So, apparently the issues: #9, #11, #17 are already closed.

**Comment by mumumilk** [comment]
@nazarepiedady is there any other issues that I can take? Im available to help

**Comment by nazarepiedady** [comment]
@mumumilk and @viniciusdeliz let me update the copy I have locally with your update,
then I will review to see what more files I can trust you to translate.

**Comment by nazarepiedady** [comment]
@viniciusdeliz and @mumumilk your next files to be translated are waiting for you brothers :+1:
