### ISSUE TITLE
docs(pt): translate `guide/best-practices/security.md`

### ISSUE THREAD

**Issue by viniciusdeliz** [nazarepiedady/vue3-docs-pt#35]

**Comment by nazarepiedady** [comment]
@viniciusdeliz 
Lamento pela demora, mas como eu tinha dito apenas a pasta da API está aberta para receber contribuições, porque eu já estou a trabalhar sobre o resto da documentação, não quero ter que lidar com conflitos agora, eu quero andar com maior cuidado possível para entregar um trabalho de qualidade.

**Comment by viniciusdeliz** [comment]
> @viniciusdeliz Lamento pela demora, mas como eu tinha dito apenas a pasta da API está aberta para receber contribuições, porque eu já estou a trabalhar sobre o resto da documentação, não quero ter que lidar com conflitos agora, eu quero andar com maior cuidado possível para entregar um trabalho de qualidade.

Issue was created just for organization purposes as I walked through the referenced links in the API section. You could've just assigned it to yourself so nobody else would take it. That's still what I suggest to handle the articles in this repo, in this way we will be able to track what is completed and what is still pending.

A _issue_ foi aberta apenas para fins de organização conforme eu traduzia a seção da API e conferia artigos referenciados que ainda estavam em inglês. Você pode atribuir a task para si mesmo, assim ninguém irá fazê-la de forma duplicada ou gerar conflitos. Ainda é o procedimento que sugiro para lidarmos com os artigos neste repositório, desta maneira podemos verificar o que está completo e o que ainda está pendente.

**Comment by viniciusdeliz** [comment]
@nazarepiedady consideraria deixar a issue aberta e atribuí-la para si mesmo?

**Comment by nazarepiedady** [comment]
@viniciusdeliz, Tu tens a absoluta razão, foi precipitado em meu julgamento, e de fato como disseste é mais fácil criar **issues** de todos os documentos à traduzir e a serem traduzidos, para que não se caia no erro de alguém querer tocar em um documento que já está a ser trabalhado.

Obrigado por frisar este ponto.
