### ISSUE TITLE
Broken link in Composables playground

### ISSUE THREAD

**Issue by viniciusdeliz** [nazarepiedady/vue3-docs-pt#82]
just a heads up that this link appears to be broken now

_Originally posted by @mumumilk in https://github.com/nazarepiedady/vue3-docs-pt/pull/81#discussion_r1233085962_

Link in line 89 of composables.md file needs to be updated:

`[Experimente-o na Zona de Testes](https://play.vuejs.org/#eNqNkj1rwzAQhv/KocUOGKVzSAIdurVjoQUvJj4XlfgkJNmxMfrvPcmJkkKHLrbu69H7SlrEszFyHFDsxN6drDIeHPrBHGtSvdHWwwKDwzfNHwjQWd1DIbd9jOW3K2qq6aTJxb6pgpl7Dnmg3NS0365YBnLgsTfnxiNHACVueKe80gTKQeN3sDAIQqjignEhIvKYqMRta1acFVrsKtDEQPLYxuU7cV8Msmg2mdTilIa6gU5p27tYWKKq1c3ENphaPrGFW25+yMXsHWFaFlfiiOSvFIBJjs15QJ5JeWmaL/xYS/Mfpc9YYrPxl52ULOpwhIuiVl9k07Yvsf9VOY+EtizSWfR6xKK6itgkvQ/+fyNs6v4XJXIsPwVL+WprCiL8AEUxw5s=)   `

**Comment by nazarepiedady** [comment]
@viniciusdeliz If you try to open this link you see that the source code is broken :sweat_smile:.

But, I already updated the links right after your pull request was merged, thanks for your dedication.

**Comment by viniciusdeliz** [comment]
Solved with commit https://github.com/nazarepiedady/vue3-docs-pt/commit/0494046c7238a0a151362a7635af408882ca9233
